name: build
on: [workflow_dispatch, push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
      - name: Install
        run: pnpm i
      - name: Build
        run: pnpm build
      - name: Publish Build
        uses: actions/upload-artifact@v3
        with:
          name: www
          path: dist
